services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=journal
      - POSTGRES_PASSWORD=journal
      - POSTGRES_DB=journal
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
